# -*- coding: utf-8 -*-
"""Alocação Ótima de Motoristas às Rotas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZIuoQyewtLWHnxgpcK3eWBLnnk-6XREV
"""

import pandas as pd
import os

def carregar_dados(pasta):
    # Extract the dataset type (e.g., 'pequeno', 'medio') from the 'pasta' argument
    dataset_type = os.path.basename(pasta)

    motoristas = pd.read_csv(
        os.path.join("/content", f"motoristas{dataset_type}.csv")
    )

    rotas = pd.read_csv(
        os.path.join("/content", f"rotas{dataset_type}.csv")
    )

    custos = pd.read_csv(
        os.path.join("/content", f"custos{dataset_type}.csv")
    )

    return motoristas, rotas, custos

def algoritmo_guloso(custos):

    atribuicoes = []

    motoristas_usados = set()
    rotas_usadas = set()

    custo_total = 0

    custos_ordenados = custos.sort_values(
        by="custo"
    )

    for _, linha in custos_ordenados.iterrows():

        motorista = linha["id_motorista"]
        rota = linha["id_rota"]
        custo = linha["custo"]

        if (
            motorista not in motoristas_usados
            and rota not in rotas_usadas
        ):

            atribuicoes.append(
                (motorista, rota, custo)
            )

            motoristas_usados.add(motorista)
            rotas_usadas.add(rota)

            custo_total += custo

    return atribuicoes, custo_total

import numpy as np
from scipy.optimize import linear_sum_assignment

def algoritmo_hungaro(
    motoristas,
    rotas,
    custos
):

    ids_motoristas = (
        motoristas["id_motorista"]
        .tolist()
    )

    ids_rotas = (
        rotas["id_rota"]
        .tolist()
    )

    matriz = np.zeros(
        (
            len(ids_motoristas),
            len(ids_rotas)
        )
    )

    for i, m in enumerate(ids_motoristas):

        for j, r in enumerate(ids_rotas):

            valor = custos[
                (custos["id_motorista"] == m)
                &
                (custos["id_rota"] == r)
            ]["custo"].values[0]

            matriz[i][j] = valor

    linhas, colunas = (
        linear_sum_assignment(matriz)
    )

    atribuicoes = []
    custo_total = 0

    for i, j in zip(linhas, colunas):

        custo = matriz[i][j]

        atribuicoes.append(
            (
                ids_motoristas[i],
                ids_rotas[j],
                custo
            )
        )

        custo_total += custo

    return atribuicoes, custo_total

import time


def imprimir_tabela(
    titulo,
    atribuicoes,
    custo_total
):

    print("\n")
    print("=" * 60)
    print(titulo)
    print("=" * 60)

    print(
        f"{'Motorista':<15}"
        f"{'Rota':<10}"
        f"{'Custo':<10}"
    )

    print("-" * 60)

    for m, r, c in atribuicoes:

        print(
            f"{m:<15}"
            f"{r:<10}"
            f"{c:<10}"
        )

    print("-" * 60)

    print(
        f"CUSTO TOTAL = {custo_total}"
    )


def executar_teste(nome, pasta):

    print("\n")
    print("#" * 60)
    print(f"TESTE {nome}")
    print("#" * 60)

    motoristas, rotas, custos = (
        carregar_dados(pasta)
    )

    inicio = time.perf_counter()

    atrib_gulosa, custo_guloso = (
        algoritmo_guloso(custos)
    )

    tempo_guloso = (
        time.perf_counter()
        - inicio
    )

    inicio = time.perf_counter()

    atrib_otima, custo_otimo = (
        algoritmo_hungaro(
            motoristas,
            rotas,
            custos
        )
    )

    tempo_hungaro = (
        time.perf_counter()
        - inicio
    )

    imprimir_tabela(
        "ALGORITMO GULOSO",
        atrib_gulosa,
        custo_guloso
    )

    imprimir_tabela(
        "ALGORITMO HÚNGARO",
        atrib_otima,
        custo_otimo
    )

    economia = (
        custo_guloso
        - custo_otimo
    )

    print("\nRELATÓRIO")

    print(
        f"Motoristas: {len(motoristas)}"
    )

    print(
        f"Rotas: {len(rotas)}"
    )

    print(
        f"Custo Guloso: {custo_guloso}"
    )

    print(
        f"Custo Húngaro: {custo_otimo}"
    )

    print(
        f"Economia: {economia}"
    )

    print(
        f"Tempo Guloso: "
        f"{tempo_guloso:.6f}s"
    )

    print(
        f"Tempo Húngaro: "
        f"{tempo_hungaro:.6f}s"
    )


def main():

    executar_teste(
        "PEQUENO (4x4)",
        "../data/pequeno"
    )

    executar_teste(
        "MÉDIO (10x10)",
        "../data/medio"
    )


if __name__ == "__main__":
    main()